import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/store/provider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import { NextAuthProvider } from "../lib/authProvider";
import SnackProvider from "@/lib/SnackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <SnackProvider>
          <Providers>
            <NextAuthProvider session={session}>{children}</NextAuthProvider>
          </Providers>
        </SnackProvider>
      </body>
    </html>
  );
}
